import React from "react"
import { Popover } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Popover,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=1489%3A11841",
  {
    props: {},
    example: (props) => (
      <Popover open={/* TODO */} anchorEl={/* TODO */} onClose={/* TODO */} />
    ),
  },
)
