import React from "react"
import { Stepper } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Stepper,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6576%3A50986",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "optionalContent": figma.string('Optional Content'),
      // "stepTitleContent": figma.string('Step Title Content'),
      // "optional": figma.boolean('Optional'),
      // "text": figma.enum('Text', {
      //   "Center": "center",
      //   "Left": "left"
      // }),
      // "state": figma.enum('State', {
      //   "Active": "active",
      //   "Inactive": "inactive",
      //   "Complete": "complete",
      //   "Error": "error",
      //   "Warning": "warning",
      //   "Info": "info",
      //   "Success": "success"
      // })
    },
    example: (props) => <Stepper steps={/* TODO */} />,
  },
)
