import React from "react"
import { ToggleButton } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ToggleButton,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6601%3A50975",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
      }),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      selected: figma.boolean("Selected"),
      // No matching props could be found for these Figma properties:
      // "icon": figma.instance('Icon'),
      // "icon": figma.boolean('Icon?'),
      // "text": figma.boolean('Text?')
    },
    example: (props) => (
      <ToggleButton
        value={/* TODO */}
        size={props.size}
        disabled={props.disabled}
        selected={props.selected}
      />
    ),
  },
)
