import figma from "@figma/code-connect";
import {AccessibilityNewOutlined, AccessibilityOutlined, AccessibleForwardOutlined, AccessibleOutlined, AccountCircleOutlined, AddReactionOutlined, AirlineSeatFlatAngledOutlined, AirlineSeatFlatOutlined, AirlineSeatIndividualSuiteOutlined, AirlineSeatLegroomExtraOutlined, AirlineSeatLegroomNormalOutlined, AirlineSeatLegroomReducedOutlined, AirlineSeatReclineExtraOutlined, AirlineSeatReclineNormalOutlined, AttributionOutlined, BabyChangingStationOutlined, BadgeOutlined, BoyOutlined, Certificate, ChangeUser, ChangeUser2, ChildCareOutlined, ChildFriendlyOutlined, CoPresentOutlined, Code, ConnectWithoutContactOutlined, ContactMailOutlined, ContactPhoneOutlined, ContactsOutlined, DirectionsRunOutlined, DirectionsWalkOutlined, DownhillSkiingOutlined, ElderlyOutlined, ElderlyWomanOutlined, ElevatorOutlined, EmojiPeopleOutlined, EngineeringOutlined, EscalatorWarningOutlined, Experience, FaceOutlined, FaceRetouchingNaturalOutlined, FaceRetouchingOffOutlined, FamilyRestroomOutlined, FollowtheSignsOutlined, GirlOutlined, GroupAddOutlined, GroupRemoveOutlined, GroupsOutlined, HailOutlined, HikingOutlined, HowtoRegOutlined, InterpreterModeOutlined, ManOutlined, ManageAccountsOutlined, NoAccountsOutlined, NordicWalkingOutlined, NotAccessibleOutlined, PeopleAltOutlined, PermContactCalendarOutlined, PermIdentityOutlined, PersonAddAlt1Outlined, PersonAddDisabledOutlined, PersonAddOutlined, PersonOffOutlined, PersonPinOutlined, PersonRemoveOutlined, PersonSearchOutlined, PortraitOutlined, PregnantWomanOutlined, PsychologyOutlined, RowingOutlined, SelfImprovementOutlined, SentimentDissatisfiedOutlined, SentimentNeutralOutlined, SentimentSatisfiedAltOutlined, SentimentVeryDissatisfiedOutlined, SentimentVerySatisfiedOutlined, SettingsAccessibilityOutlined, SkateboardingOutlined, SleddingOutlined, SnowboardingOutlined, SnowshoeingOutlined, SocialDistanceOutlined, SportsHandballOutlined, SportsKabaddiOutlined, SportsMartialArtsOutlined, SupervisedUserCircleOutlined, SupervisorAccountOutlined, SupportAgentOutlined, SurfingOutlined, TransferWithinaStationOutlined, WcOutlined, WomanOutlined} from "icons";




























































































