import React from "react"
import { Autocomplete } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Autocomplete,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6570%3A49856",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      multiple: figma.boolean("Multiple Value"),
      open: figma.boolean("Open"),
    },
    example: (props) => (
      <Autocomplete
        options={/* TODO */}
        renderInput={/* TODO */}
        multiple={props.multiple}
        open={props.open}
      />
    ),
  },
)
