import React from "react"
import { Rating } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Rating,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6562%3A39624",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      size: figma.enum("Size", {
        Small: "small",
        "Medium*": "medium",
        Large: "large",
      }),
      disabled: figma.boolean("Disabled"),
    },
    example: (props) => <Rating size={props.size} disabled={props.disabled} />,
  },
)
