import React from "react"
import { Badge } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Badge,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6587%3A47500",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      color: figma.enum("Color", {
        Primary: "primary",
        Secondary: "secondary",
        Error: "error",
        Info: "info",
        Success: "success",
        Warning: "warning",
      }),
      variant: figma.enum("Variant", {
        Standard: "standard",
        Dot: "dot",
      }),
      // No matching props could be found for these Figma properties:
      // "content": figma.string('Content')
    },
    example: (props) => <Badge color={props.color} variant={props.variant} />,
  },
)
