import React from "react"
import { Button } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6543%3A36744",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      color: figma.enum("Color", {
        Inherit: "inherit",
        Primary: "primary",
        Secondary: "secondary",
        Success: "success",
        Error: "error",
        Info: "info",
        Warning: "warning",
      }),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
      }),
      variant: figma.enum("Variant", {
        Text: "text",
        Outlined: "outlined",
        Contained: "contained",
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "startIcon": figma.instance('↳ Start Icon'),
      // "endIcon": figma.instance('↳ End Icon'),
      // "endIcon": figma.boolean('End Icon'),
      // "startIcon": figma.boolean('Start Icon')
    },
    example: (props) => (
      <Button
        color={props.color}
        disabled={props.disabled}
        size={props.size}
        variant={props.variant}
      />
    ),
  },
)
