import React from "react"
import { Paper } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Paper,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6584%3A46711",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      square: figma.boolean("Square"),
      variant: figma.enum("Variant", {
        Elevation: "elevation",
        Outlined: "outlined",
      }),
      children: figma.instance("*"),
      // No matching props could be found for these Figma properties:
      // "instance": figma.instance('↳ Instance'),
      // "instanceSlot": figma.boolean('Instance Slot?'),
      // "elevation": figma.enum('Elevation', {
      //   "0": "0",
      //   "1": "1",
      //   "2": "2",
      //   "3": "3",
      //   "4": "4",
      //   "5": "5",
      //   "6": "6",
      //   "7": "7",
      //   "8": "8",
      //   "9": "9",
      //   "10": "10",
      //   "11": "11",
      //   "12": "12",
      //   "13": "13",
      //   "14": "14",
      //   "15": "15",
      //   "16": "16",
      //   "17": "17",
      //   "18": "18",
      //   "19": "19",
      //   "20": "20",
      //   "21": "21",
      //   "22": "22",
      //   "23": "23",
      //   "24": "24"
      // })
    },
    example: ({ children, ...rest }) => <Paper {...rest}>{children}</Paper>,
  },
)
