import React from "react"
import { List } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  List,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=11566%3A157133",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      dense: figma.boolean("Dense"),
      disablePadding: figma.boolean("Dis. Padding"),
    },
    example: (props) => (
      <List dense={props.dense} disablePadding={props.disablePadding} />
    ),
  },
)
