import React from "react"
import { SpeedDial } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SpeedDial,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6599%3A50822",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      direction: figma.enum("Direction", {
        Up: "up",
        Down: "down",
        Left: "left",
        Right: "right",
      }),
      // No matching props could be found for these Figma properties:
      // "instance": figma.instance('Instance')
    },
    example: (props) => (
      <SpeedDial
        icon={/* TODO */}
        actions={/* TODO */}
        direction={props.direction}
        ariaLabel={/* TODO */}
      />
    ),
  },
)
