import React from "react"
import { Tabs } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tabs,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6579%3A45104",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      orientation: figma.enum("Orientation", {
        Horizontal: "horizontal",
        Vertical: "vertical",
      }),
      textColor: figma.enum("Active Color", {
        Secondary: "secondary",
        Primary: "primary",
      }),
      // No matching props could be found for these Figma properties:
      // "text": figma.boolean('Text'),
      // "tabContent": figma.string('Tab Content'),
      // "icon": figma.boolean('Icon'),
      // "active": figma.boolean('Active'),
      // "iconPosition": figma.enum('Icon Position', {
      //   "Up": "up",
      //   "Left": "left",
      //   "Right": "right"
      // }),
      // "state": figma.enum('State', {
      //   "Enabled": "enabled",
      //   "Disabled": "disabled",
      //   "Focused": "focused",
      //   "Pressed": "pressed"
      // })
    },
    example: (props) => (
      <Tabs
        tabs={/* TODO */}
        orientation={props.orientation}
        textColor={props.textColor}
      />
    ),
  },
)
