import React from "react"
import { Container } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Container,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=7660%3A81184",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disableGutters: figma.boolean("Dis. Gutters"),
      maxWidth: figma.enum("Max Width", {
        Small: "sm",
      }),
    },
    example: (props) => (
      <Container
        disableGutters={props.disableGutters}
        maxWidth={props.maxWidth}
      />
    ),
  },
)
