import figma from "@figma/code-connect";
import {Account, AccountInfo, AccountRep, AccountRepDasboard, AccountRepInfo, AutosaveNew, CalendarViewDayOutlined, CasesOutlined, DataThresholdingOutlined, DensityLargeOutlined, DensityMediumOutlined, DensitySmallOutlined, DragHandleOutlined, DragIndicatorOutlined, ExittoAppOutlined, FullscreenExitOutlined, FullscreenOutlined, HomeOutlined, HorizontalSplitOutlined, InputOutlined, IosShareOutlined, LoginOutlined, LogoutOutlined, MaximizeOutlined, MemoryOutlined, MenuOutlined, MinimizeOutlined, MoreHorizOutlined, MoreOutlined, MoreVertOutlined, OpeninBrowserOutlined, OpeninNewOffOutlined, OpeninNewOutlined, Operations, PMDashboard, RemoveOutlined, ReorderOutlined, SaveManually, ShowFile, SystemUpdateAltOutlined, TableRowsFilled, ViewColumnFilled, ViewDayOutlined, ViewHeadlineOutlined, ViewHeadlineOutlined, ViewModuleOutlined, ViewStreamFilled, ViewTimelineOutlined, WidgetsOutlined} from "icons";
















































