import React from "react"
import { Switch } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Switch,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6564%3A39128",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      color: figma.enum("Color", {
        Primary: "primary",
        Secondary: "secondary",
        Error: "error",
        Info: "info",
        Success: "success",
        Warning: "warning",
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      checked: figma.boolean("Checked"),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
    },
    example: (props) => (
      <Switch
        color={props.color}
        size={props.size}
        checked={props.checked}
        disabled={props.disabled}
      />
    ),
  },
)
