import figma from "@figma/code-connect";
import {AddNote, AddchartOutlined, AppRegistrationOutlined, AppsOutageOutlined, AppsOutlined, AutoAwesomeMotionOutlined, Autosave, CancelOutlined, ClearAllOutlined, ContentCopyOutlined, ContentCutOutlined, ContentPasteOffOutlined, ContentPasteOutlined, ContentPasteSearchOutlined, CopyAllOutlined, DescriptionOutlined, DifferenceOutlined, DownloadFilled, DownloadforOfflineOutlined, FeedOutlined, FileCopyOutlined, FileDownloadOffOutlined, FileDownloadOutlined, FileOpenOutlined, FilePresentOutlined, FileUploadOutlined, FilterAltOffOutlined, FilterAltOutlined, FilterListOffOutlined, FilterListOutlined, FilterNoneOutlined, FindinPageOutlined, FlipOutlined, FliptoBackOutlined, FliptoFrontOutlined, If, InboxOutlined, InsertDriveFileOutlined, InsertPageBreakOutlined, Inventory2Outlined, InventoryOutlined, LibraryAddOutlined, LibraryBooksOutlined, LibraryMusicOutlined, ListAltOutlined, ListOutlined, NoteAddOutlined, NotesOutlined, OutboxOutlined, POnotready, POnotready, PhotoSizeSelectSmallOutlined, PlagiarismOutlined, PlaylistAddCheckCircleOutlined, PlaylistAddCheckOutlined, PlaylistAddCircleOutlined, PlaylistAddOutlined, PlaylistPlayOutlined, PlaylistRemoveOutlined, RestorePageOutlined, RoundedCornerOutlined, SaveAltFilled, SegmentOutlined, SelectAllOutlined, ShortTextOutlined, SortOutlined, StickyNote2Outlined, SubjectOutlined, TabOutlined, TabUnselectedOutlined, TaskOutlined, Template, TextSnippetOutlined, TocOutlined, UnarchiveOutlined, UploadFileOutlined} from "icons";











































































