import figma from "@figma/code-connect";
import {AddTaskOutlined, AssignmentLateOutlined, AssignmentOutlined, AssignmentTurnedinOutlined, BeenhereOutlined, CheckCircleFilled, CheckCircleOutlined, ContactPageOutlined, DiscFullOutlined, DomainVerificationOutlined, DoneAllOutlined, DoneOutlineOutlined, DoneOutlined, ErrorOutlineOutlined, ErrorOutlined, FactCheckOutlined, FileDownloadDoneOutlined, FlagFilled, FlagOutlined, GradingOutlined, HelpCenterOutlined, HelpOutlineOutlined, HelpOutlined, InfoFilled, InfoOutlined, LibraryAddCheckOutlined, NewReleasesOutlined, PriorityHighOutlined, PublishedWithChangesOutlined, RemoveDoneOutlined, ReportOffOutlined, ReportOutlined, RunningWithErrorsOutlined, SdCardAlertOutlined, SpellcheckOutlined, TaskAltOutlined, UnpublishedOutlined, VerifiedOutlined, WarningAmberOutlined, WarningOutlined} from "icons";







































