import React from "react"
import { Select } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Select,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6570%3A41424",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      variant: figma.enum("Variant", {
        Filled: "filled",
        Outlined: "outlined",
        Standard: "standard",
      }),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      error: figma.enum("State", {
        Error: true,
      }),
      labelId: figma.string("Label"),
      native: figma.boolean("Active"),
      // No matching props could be found for these Figma properties:
      // "value": figma.string('↳ Value'),
      // "placeholder": figma.string('↳ Placeholder'),
      // "label": figma.string('Label'),
      // "startInstance": figma.instance('Start Instance'),
      // "placeholder": figma.boolean('Placeholder?'),
      // "adornStart": figma.boolean('Adorn. Start?'),
      // "value": figma.boolean('Value?'),
      // "helper": figma.boolean('Helper?'),
      // "hasValue": figma.boolean('Has Value')
    },
    example: (props) => (
      <Select
        label={props.label}
        size={props.size}
        variant={props.variant}
        disabled={props.disabled}
        error={props.error}
        labelId={props.labelId}
        native={props.native}
      />
    ),
  },
)
