import figma from "@figma/code-connect";
import {AccountBalanceOutlined, ApartmentOutlined, AssuredWorkloadOutlined, BungalowOutlined, BusinessOutlined, CabinOutlined, CastleOutlined, ChaletOutlined, ChurchOutlined, CorporateFareOutlined, CottageOutlined, CountertopsOutlined, DomainAddOutlined, DomainDisabledOutlined, DoorFrontOutlined, DoorSlidingOutlined, FactoryOutlined, FenceOutlined, FestivalOutlined, FortOutlined, FoundationOutlined, HolidayVillageOutlined, HomeWorkOutlined, HouseOutlined, HouseSidingOutlined, HouseboatOutlined, LocationCityOutlined, MapsHomeWorkOutlined, MarginOutlined, StadiumOutlined, SynagogueOutlined, TaxRates, TempleBuddhistOutlined, TempleHinduOutlined, VillaOutlined, WarehouseOutlined} from "icons";



































