import React from "react"
import { Alert } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Alert,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6595%3A48211",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      severity: figma.enum("Severity", {
        Error: "error",
        Warning: "warning",
        Info: "info",
        Success: "success",
      }),
      variant: figma.enum("Variant", {
        Filled: "filled",
        Outlined: "outlined",
        Standard: "standard",
      }),
      // No matching props could be found for these Figma properties:
      // "title": figma.string('↳ Title'),
      // "description": figma.string('↳ Description'),
      // "description": figma.boolean('Description?'),
      // "instance": figma.instance('↳Instance'),
      // "title": figma.boolean('Title?'),
      // "action": figma.boolean('Action?'),
      // "onClose": figma.boolean('On Close?')
    },
    example: (props) => (
      <Alert severity={props.severity} variant={props.variant} />
    ),
  },
)
