import React from "react"
import { Checkbox } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6543%3A43052",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      checked: figma.boolean("Checked"),
      color: figma.enum("Color", {
        Primary: "primary",
        Secondary: "secondary",
        Error: "error",
        Info: "info",
        Success: "success",
        Warning: "warning",
        Default: "default",
      }),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      indeterminate: figma.boolean("Indeterminate"),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
      }),
    },
    example: (props) => (
      <Checkbox
        checked={props.checked}
        color={props.color}
        disabled={props.disabled}
        indeterminate={props.indeterminate}
        size={props.size}
      />
    ),
  },
)
