import React from "react"
import { ButtonGroup } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ButtonGroup,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6543%3A39843",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      color: figma.enum("Color", {
        Inherit: "inherit",
        Primary: "primary",
        Secondary: "secondary",
        Error: "error",
        Info: "info",
        Success: "success",
        Warning: "warning",
      }),
      orientation: figma.enum("Orientation", {
        Horizontal: "horizontal",
        Vertical: "vertical",
      }),
      variant: figma.enum("Variant", {
        Text: "text",
        Contained: "contained",
        Outlined: "outlined",
      }),
    },
    example: (props) => (
      <ButtonGroup
        color={props.color}
        orientation={props.orientation}
        variant={props.variant}
      />
    ),
  },
)
