import React from "react"
import { Dialog } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Dialog,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6586%3A47183",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      maxWidth: figma.enum("Max Width", {
        xs: "xs",
        sm: "sm",
        md: "md",
        lg: "lg",
        xl: "xl",
      }),
    },
    example: (props) => (
      <Dialog
        open={/* TODO */}
        onClose={/* TODO */}
        maxWidth={props.maxWidth}
      />
    ),
  },
)
