import figma from "@figma/code-connect";
import {AccessAlarmOutlined, AccessTimeOutlined, AddAlarmOutlined, AddAlertOutlined, AlarmOffOutlined, AlarmonOutlined, AvTimerOutlined, Availability, CalendarTodayOutlined, CircleNotificationsOutlined, DateRangeOutlined, DoorbellOutlined, EditNotificationsOutlined, EventAvailableOutlined, EventBusyOutlined, EventNoteOutlined, EventOutlined, EventRepeatOutlined, HistoryToggleOffOutlined, HourglassBottomOutlined, HourglassDisabledOutlined, HourglassEmptyOutlined, HourglassFullOutlined, HourglassTopOutlined, MoreTimeOutlined, NotificationAddOutlined, NotificationImportantOutlined, NotificationsActiveOutlined, NotificationsOffOutlined, NotificationsOutlined, NotificationsPausedOutlined, PunchClockOutlined, QueryBuilderFilledOutlined, RestoreOutlined, Timer10Outlined, Timer10SelectOutlined, Timer3Outlined, Timer3SelectOutlined, TimerOffOutlined, TimerOutlined, UpdateDisabledOutlined, UpdateOutlined, WatchOffOutlined, WatchOutlined} from "icons";











































