import React from "react"
import { TextField } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TextField,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6570%3A48313",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      variant: figma.enum("Variant", {
        Filled: "filled",
        Outlined: "outlined",
        Standard: "standard",
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      label: figma.string("Label"),
      placeholder: figma.string("↳ Placeholder"),
      value: figma.string("↳ Value"),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      error: figma.enum("State", {
        Error: true,
      }),
      focused: figma.enum("State", {
        Focused: true,
      }),
      // No matching props could be found for these Figma properties:
      // "placeholder": figma.string('↳ Placeholder'),
      // "value": figma.string('↳ Value'),
      // "endInstance": figma.instance('↳ End Instance'),
      // "startInstance": figma.instance('↳ Start Instance'),
      // "value": figma.boolean('Value?'),
      // "label": figma.string('Label'),
      // "adornStart": figma.boolean('Adorn. Start?'),
      // "helper": figma.boolean('Helper?'),
      // "placeholder": figma.boolean('Placeholder?'),
      // "adornEnd": figma.boolean('Adorn. End?'),
      // "typeNumber": figma.boolean('Type: number?'),
      // "hasValue": figma.boolean('Has Value')
    },
    example: (props) => (
      <TextField
        variant={props.variant}
        size={props.size}
        label={props.label}
        placeholder={props.placeholder}
        value={props.value}
        disabled={props.disabled}
        error={props.error}
        focused={props.focused}
      />
    ),
  },
)
