import React from "react"
import BottomNavigation from "./BottomNavigation.stories"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  BottomNavigation,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6572%3A50288",
  {
    props: {
      labelContent: figma.string("Label Content"),
      active: figma.boolean("Active"),
      label: figma.boolean("Label"),
      state: figma.enum("State", {
        Enabled: "enabled",
        Focused: "focused",
        Disabled: "disabled",
        Pressed: "pressed",
      }),
    },
    example: (props) => <BottomNavigation />,
  },
)
