import React from "react"
import { BottomNavigation } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  BottomNavigation,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6572%3A50307",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "iconOnly": figma.boolean('Icon Only'),
      // "items": figma.enum('Items', {
      //   "Three": "three",
      //   "Four": "four"
      // })
    },
    example: (props) => <BottomNavigation />,
  },
)
