import React from "react"
import { Chip, ChipProps } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Chip,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6588%3A47683",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      color: figma.enum("Color", {
        Default: "default",
        Primary: "primary",
        Secondary: "secondary",
        Error: "error",
        Info: "info",
        Success: "success",
        Warning: "warning",
      }),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      variant: figma.enum("Variant", {
        Outlined: "outlined",
        Filled: "filled",
      }),
      // No matching props could be found for these Figma properties:
      onDelete: figma.boolean('Delete?', {
        true: figma.children('*'),
        // true: () => { },
        false: undefined
      }),
      thumbnail: figma.boolean('Thumbnail?', {
        true: figma.children('*'),
        false: undefined
      }),
    },
    example: (props: ChipProps) => (
      <Chip {...props} />
    ),
  },
)
