import React from "react"
import { Table } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Table,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6594%3A46634",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "tableFooter": figma.boolean('TableFooter?'),
      // "small": figma.boolean('Small'),
      // "checkbox": figma.boolean('Checkbox'),
      // "smallScreen": figma.boolean('Small Screen'),
      // "rows": figma.enum('Rows', {
      //   "5": "5",
      //   "10": "10"
      // })
    },
    example: (props) => <Table columns={/* TODO */} rows={/* TODO */} />,
  },
)
