import React from "react"
import { Avatar } from "./index"
import { Badge } from "@mui/material"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Avatar,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6587%3A47403",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      variant: figma.enum("Variant", {
        Circular: "circular",
        Rounded: "rounded",
        Square: "square",
      }),
      alt: figma.string("Initials"),
      // No matching props could be found for these Figma properties:
      initials: figma.string('Initials'),
      badge: figma.boolean('Badge', {
        // true: figma.children('*'),
        true: <Badge />,
        false: undefined
      }),
      size: figma.enum('Size', {
        "40px": "40px",
        "32px": "32px",
        "24px": "24px",
        "18px": "18px"
      }),
      content: figma.enum('Content', {
        "Text": "text",
        "Icon": "icon",
        "Image": "image"
      })
    },
    example: (props) => <Avatar {...props} />,
  },
)
