import React from "react"
import { Tooltip } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Tooltip,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6590%3A48770",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "direction": figma.enum('Direction', {
      //   "None": "none",
      //   "Down": "down",
      //   "Up": "up",
      //   "Left": "left",
      //   "Right": "right"
      // })
    },
    example: (props) => <Tooltip title={/* TODO */} />,
  },
)
