import React from "react"
import { SvgIconButton } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  SvgIconButton,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=11673%3A12740",
  {
    props: {
      // children: figma.string("Children"),
    },
    example: (props) => <SvgIconButton {...props} />
  },
)
