import { Accordion, AccordionProps } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Accordion,
  "https://www.figma.com/design/cwXEuR3Mbo0Me3HHLFNdKG/MUI-for-Figma-v6.1.0---Material-UI?node-id=6583%3A46084",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.boolean("Disabled"),
      children: figma.children('*'),
      // title: figma.string("Title"),
      // expanded: figma.boolean("Expanded?"),
      // No matching props could be found for these Figma properties:
      // "instance": figma.instance('↳ Instance'),
      // "firstoftype": figma.boolean('First-of-type'),
      // "lastoftype": figma.boolean('Last-of-type')
    },
    example: ({ children, ...rest }: AccordionProps) => (
      <Accordion {...rest}>{children}</Accordion>
    ),
  },
)
