import React from "react"
import { Accordion } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Accordion,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6583%3A46084",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.boolean("Disabled"),
      expanded: figma.boolean("Expanded?"),
      // No matching props could be found for these Figma properties:
      // "instance": figma.instance('↳ Instance'),
      // "firstoftype": figma.boolean('First-of-type'),
      // "lastoftype": figma.boolean('Last-of-type')
    },
    example: (props) => (
      <Accordion disabled={props.disabled} expanded={props.expanded} />
    ),
  },
)
