import React from "react"
import { Link } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Link,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6574%3A50682",
  {
    props: {
      color: figma.enum("Color", {
        Primary: "primary",
        Inherit: "inherit",
      }),
      underline: figma.enum("Underline", {
        Always: "always",
        Hover: "hover",
        None: "none",
      }),
      state: figma.enum("State", {
        Enabled: "enabled",
        Hovered: "hovered",
        Focused: "focused",
      }),
    },
    example: (props) => <Link />,
  },
)
