import React from "react"
import { Slider } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Slider,
  "https://www.figma.com/design/BpvKv4FZpzUKLb9nzDLm9Q/ELEKS-UI---Components?node-id=6562%3A39045",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      orientation: figma.enum("Orientation", {
        Horizontal: "horizontal",
        Vertical: "vertical",
      }),
      color: figma.enum("Color", {
        Primary: "primary",
        Secondary: "secondary",
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.boolean('Label'),
      // "values": figma.boolean('Values'),
      // "variant": figma.enum('Variant', {
      //   "Continuous": "continuous",
      //   "Marks": "marks",
      //   "Range": "range"
      // })
    },
    example: (props) => (
      <Slider
        disabled={props.disabled}
        orientation={props.orientation}
        color={props.color}
        size={props.size}
      />
    ),
  },
)
